apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: quarkus-maven-build
spec:
  params:
    - description: url of the git repository to clone
      name: url
      type: string
  tasks:
    - name: rm-workspace
      taskRef:
        name: rm-workspace
      workspaces:
        - name: project-dir
          workspace: project-dir

    - name: git-clone
      runAfter:
        - rm-workspace
      params:
        - name: url
          value: $(params.url)
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: project-dir
          workspace: project-dir

    - name: maven-build-image-deploy
      runAfter:
        - git-clone
      params:
        - name: GOALS
          value:
            - quarkus:deploy
            - -B
            - -Dquarkus.kubernetes.deploy=false
            - -Dquarkus.container-image.build=true
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: project-dir
          workspace: project-dir
  workspaces:
    - name: project-dir
    - name: maven-m2-repo
    - name: maven-settings